### ISSUE TITLE
Suggestion about providing WIFI SSID and PASSWD in a better way

### ISSUE THREAD

**Issue by ZuoJiawei** [foss-for-synopsys-dwc-arc-processors/embarc_osp#8]
# Issue Summary
- **Type**: *Enhancement*
- **Category**: *Example* 
- **Priority**: *Medium*
- **Release Version**: 2017.03
--------------------------------------------------------------------------------
# Development Environment
- **HOST OS**
    Windows 10, 64Bit 
- **TOOLCHAIN**
    ARC GNU 2017.03.
- **BOARD**
    EMSK 1.1
- **ARC CORE**
    EM6
--------------------------------------------------------------------------------
# Enhancement
   Wifi name and code should be notified to users about their location,though I know they are in  
   /board/board.h,they are hard to be found by users from scratch.
   For instance:
   ### Extra Comments
   Wifi name and password is located in **/board/board.h**,please be sure the wifi git is correctly 
   detached before the test.

**Comment by fanghuaqi** [comment]
1. The header file where WiFi SSID and PASSWD located actually located in each board's header file, for example, such as emsk board, it located in emsk.h, and the emsk.h is included by board.h. 
2. About where to get the WiFi name, for current release, we suggest developer to read the [embARC documentation - example](http://embarc.org/embarc_osp/doc/embARC_Document/html/page_example.html) section first.
3. And about configuration of WiFi SSID and PASSWD, currently you can found it [here](http://embarc.org/embarc_osp/doc/embARC_Document/html/page_example_usage.html#subsect_example_usage_PFE_SetupBoardEnv)
4. Since all examples related to Network and WiFi, developer should setup a WiFi hotspot, and the SSID and PASSWD most of the time keep the same for your development, so it just need to be changed once, and effected for all examples.
